addSbtPlugin("com.github.sbt"    % "sbt-release"    % "1.4.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.14.3")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.10.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.4.0")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.11.0")
